# Generated by Django 5.0.4 on 2024-05-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_alter_product_description_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='imagen_default.jpg', upload_to='products', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_type',
            field=models.CharField(choices=[('unitario', 'Precio Unitario'), ('media-doc', 'Media Docena'), ('docena', 'Docena'), ('por-kilo', 'kilo')], default='unitario', max_length=20, verbose_name='Tipo'),
        ),
    ]
